### ISSUE TITLE
\wick does not work with \bar.

### ISSUE THREAD

**Issue by drybalka** [JP-Ellis/simpler-wick#6]
Symbols with \bar are quite common for Dirac operators. The following code gives an error:
\wick{ \c\psi \c\bar\psi }
Without the \bar, however, it works fine.

**Comment by JP-Ellis** [comment]
The issue here is that both `\bar` and `\c` take arguments.  By default if there are no braces, LaTeX will use the next 'thing' as the argument.  So `\bar\psi` is equivalent to `\bar{\psi}`.  Given that you have no braces in what you wrote above, LaTeX understands it as:
```latex
\wick{\c{\psi} \c{\bar}\psi }
```
which is why you have the error.  What you need is to explicitly group the `\bar\psi` together:
```latex
\RequirePackage{luatex85}
\documentclass[border=10pt]{standalone}

\usepackage{simpler-wick}

\begin{document}
\(\wick{\c\psi \c{\overline\psi}} \)
\end{document}
```
![test-1](https://cloud.githubusercontent.com/assets/3196162/25516700/61c91882-2c2f-11e7-8dc2-f06e2e481b1d.png)
